using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;
using System.Linq;

namespace WpfApp
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Main(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
        {

        }

        private void ListBox_SelectionChanged(object sender, System.Windows.Controls.SelectionChangedEventArgs e)
        {
            if (DataViewTable != null)
            {
                //DataViewTable.ItemsSource = _viewModel?.CurrentTable;
                DataViewTable.InvalidateVisual();
            }
        }

        private void DataViewTable_RowEditEnding(object sender, System.Windows.Controls.DataGridRowEditEndingEventArgs e)
        {
            var a = (DataGrid)sender;
            var c = (ObservableCollection<object>)a.ItemsSource;
            if (this.DataViewTable.SelectedItem != null)
            {
                //var a = (sender as DataGrid);
                a.RowEditEnding -= DataViewTable_RowEditEnding;
                a.CommitEdit();
                a.Items.Refresh();
                a.RowEditEnding += DataViewTable_RowEditEnding;
            }
            else return;
        }

        private void DataViewTable_AutoGeneratedColumns(object sender, System.EventArgs e)
        {

        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            _viewModel.SaveData(new ObservableCollection<object>(this.DataViewTable.ItemsSource.Cast<object>()));
        }
    }
}
